BMIcalcapp/urls.py
from django.urls import path
from BMIcalcapp.views import bmi_calculator, bmi_data_entry, save_data, dashboard, delete_data

app_name = "BMIcalculator" 

urlpatterns = [
    path("entry/", bmi_data_entry, name="data_entry" ),
    path("calculate-bmi/", bmi_calculator, name="bmi_calculator"),
    path('save/', save_data, name="save"),
    path('dashboard/' ,dashboard, name="dashboard"),
    path('delete-data/', delete_data, name="delete"),
]
 

BMIcalculator/urls.py
from django.contrib import admin
from django.urls import path, include
from useraccount.views import home

app_name = "project"

urlpatterns = [
    path('', home, name="home"),
    path('admin/', admin.site.urls),
    path('bmi/', include("BMIcalcapp.urls", namespace="BMIcalculator")),
    path('user/', include('useraccount.urls', namespace="user")),
    path('verification/', include('verify_email.urls')),	

]

useraccount/urls.py
from django.urls import path
from useraccount.views import login_view, register_view, logout_view, send_suggestions, update_view
app_name = 'user'

urlpatterns = [
    path('login/', login_view, name="login"),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('send/', send_suggestions, name="send_suggestions"),
    path('update/', update_view, name="update"),
    # path('confirmation_page', send_confirmation, name="confirm"),
]

BMIcalcapp/models.py
from django.db import models

class State(models.Model):
    state = models.CharField(max_length=20, null=True, blank=True)
    lower_value = models.FloatField(null=True, blank=True)
    higher_value = models.FloatField(null=True, blank=True)
    color = models.CharField(max_length=100, null=True, blank=True)
    suggestions = models.TextField(null=True, blank=True)  

    def __str__(self):
        return str(self.lower_value) + " to " + str(self.higher_value)
    
# class BMI(models.Model):
#     weight = models.IntegerField(null=True, blank=True)
#     height = models.IntegerField(null=True, blank=True)
#     currentBMI = models.IntegerField(null=True, blank=True)

#     def __str__(self):
#         return self.weight
# from django.db import models
# from useraccount.models import UserModel
# from django.dispatch import receiver
# from django.db.models.signals import post_save

# class BMI(models.Model):
#     user = models.OneToOneField(UserModel, on_delete=models.CASCADE, null=True)
#     weight = models.IntegerField(null=True, blank=True)
#     height = models.IntegerField(null=True, blank=True)
#     date = models.DateTimeField(auto_now_add=False)
#     updated_time = models.DateTimeField(auto_now=True)


#     def __str__(self):
#         return self.weight


# @receiver(post_save, sender=UserModel)
# def bmiSave(sender, instance, created, **kwargs):
#     if created:
#         BMI.objects.create(user=instance)


# # class Suggestion(models.Model):
# #     underweight_condition = models.TextField(null=True, blank=True)
# #     normal_condition = models.TextField(null=True, blank=True)
# #     overweight_condition = models.TextField(null=True, blank=True)
# #     obese_condition = models.TextField(null=True, blank=True)


    

BMIcalcapp/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
# from BMIcalcapp.models import BMI
from django.contrib.auth.models import User
from useraccount.models import UserModel
from BMIcalcapp.models import State

@login_required
def bmi_data_entry(request):
    context = {'title': "Weight | Height | BMI"}
    return render(request, "form.html", context)


def meterify(request):
    height = (request.GET['height'])
    unit = request.GET['length_unit'] 
    if unit == "centimeter": 
        height = float(height)
        return round((height * 0.01), 2)
    elif unit == "foot" :
        if height.find(".") == 1:
            foots_and_inches = height.split(".")
            foots = float(foots_and_inches[0]) 
            inches = float(foots_and_inches[1])
            height = float(foots + (inches/12))
        else: height = float(height)
        return round((height * 0.3048), 2)
    
    elif unit == "inch" :
        height = float(height)
        
        return round((height * 0.0254), 2)
    else: return round(float(height), 2)


def kilofy(request):
    weight = float(request.GET['weight'])
    unit = request.GET['weight_unit']
    if unit == 'Pound': return round((weight *0.453592), 2)
    else: return round(weight, 2)

def get_status(BMI):
    for state in State.objects.all():
        current_state_high_value = state.higher_value
        current_state_low_value = state.lower_value
        if current_state_low_value < BMI <= current_state_high_value:
            return state

@login_required
def bmi_calculator(request):
    weight = kilofy(request)
    height = meterify(request)
    try: BMI =  round((weight / ((height)**2)), 2)
    except: return HttpResponseRedirect(reverse('BMIcalculator:data_entry'))
    state =  get_status(BMI)
    result = state.state
    message = state.suggestions
    document = f"suggestions/{result}.html"
    

    context = { 'state':state,
               'title': result.title() + ' BMI and Suggestions',
               'result': result, 
               'BMI': BMI, 
               'message':message, 
               "height":height, 
               "weight":weight,
               "length_unit":request.GET['length_unit'],
               "weight_unit":request.GET['weight_unit']
               }
    return render(request, document, context)




@login_required
def save_data(request):
    # print(request.GET)
    BMI_value = float(request.POST['BMI_value'])
    height = float(request.POST['height'])  
    weight = float(request.POST['weight'])
    # print("hey don't get confused", request.user, "id------", request.user.pk, (User.objects.filter(pk=2)))
    user = UserModel.objects.filter(user=request.user)[0]
    user.state = get_status(BMI_value)
    user.bmi = round(float(BMI_value), 2)
    user.height = round(float(height), 2)
    user.weight = round(float(weight), 2)
    user.save()

    return HttpResponseRedirect(reverse('BMIcalculator:dashboard'))

@login_required
def delete_data(request):
    user = UserModel.objects.filter(user=request.user)[0]
    user.bmi = None
    user.height = None
    user.weight = None
    user.save()
    return HttpResponseRedirect(reverse('BMIcalculator:dashboard'))
    

@login_required
def dashboard(request):
    user = UserModel.objects.filter(user=request.user)[0]
    if not user.email:
        user.email = request.user.email
        user.save()
    return render(request, 'dashboard.html', context={'user':user, 'title':"DASHBOARD"})

BMIcalcapp/templates/dashboard.html
{% extends 'base.html' %} {% load static %} {% block style %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/dashboard.css' %}"
/>

<style>
  *{
      --table-back-color:{{user.state.color}} ;
  }
</style>
{% endblock style %}

{% block content %}

<label for="table"> Your Current Data </label>
<table id="table">
  <tr>
    <th>Username</th>
    <th>Age</th>

    <th>Height(meter)</th>
    <th>Weight(kg)</th>
    <th>BMI</th>
    <th>Email</th>
    <th>Last updated</th>
  </tr>
  <tr>
    <td>{{user}}</td>
    <td>{{user.age}}</td>
    <td>{{user.height}}</td>

    <td>{{user.weight}}</td>
    <td>{{user.bmi}}</td>
    <td>{{user.email}}</td>
    <td>{{user.updated_time}}</td>
  </tr>
</table>

<form action="{% url 'BMIcalculator:delete' %}">
  <input type="submit" value="DELETE BMI DATA" id="delete" />
</form>
<form action="{% url 'user:update' %}">
  <input type="submit" value="UPDATE MY DATA" id="update" />
</form>
{% endblock content %}

BMIcalcapp/templates/form.html
{% extends 'base.html' %}
{% load static %}
{% block style %}

<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}">

{% endblock style %}

{% block content %}

<div class="container">
    <form action="{% url 'BMIcalculator:bmi_calculator' %}" method="get" id="bmi_calculator">
        <div class="form-group mb-3">

        <label for="weight"> <h1>Weight</h1>  </label>
        <input required type="number" id="weight" class="form-control" placeholder="Weight" name="weight" step="0.01">

        <select name="weight_unit"class="form-select form-select-lg mb-3 select2bs4" id="weight_unit" required>
            <option>Kilogram</option>
            <option>Pound</option>
        </select>
        <label for="height"> <h1>Height </h1></label>
        <input required type="number" id="height" class="form-control" placeholder="Height (For using foot you should put the inches after decimal)" name="height" step="0.01" max_value="4">
        <select name="length_unit" class="form-select form-select-lg mb-3 custom-select" id="length_unit" required>
            <option>meter</option>
            <option>centimeter</option>
            <option>foot</option>
            <option>inch</option>
        </select>
        <input type="submit" class="btn btn-primary" value="Calculate BMI">
        </div>
    </form>
</div>

{% endblock content %}

</html>

BMIcalcapp/templates/result.html
{% extends 'base.html' %} {% load static %} {% block style %}

<link rel="stylesheet" type="text/css" href="{% static 'css/result.css' %}" />

<style>
  body {
    background-color: var(--p-back-color);
    background-size: 70vw 100vh;
    background-repeat: no-repeat;
    background-position: center;
    background-attachment: fixed;
    background-image: url('{% get_static_prefix %}{{state.state}}.jpg');
    --p-back-color: {{state.color}};

  }
</style>

{% endblock style %} {% block content %}
<p>You have a BMI of {{BMI}}, which means you're {{result}}</p>

<p>
  {{message}}
  <br />
  {% if result != 'normal' %} Your BMI needs to be between 18.5 and 25 to be in
  you perfect physic. Try to be fit and healthy. {% else %} Although you're in
  the perfect shape and size. You maybe unhealthy due to lifestyle. Keep your
  strong physic consistent. {% endif %}
</p>

<form action="{% url 'BMIcalculator:save' %}" method="POST">
  {% csrf_token %}
  <input type="hidden" name="BMI_value" value="{{BMI}}" />
  <input type="hidden" name="height" value="{{height}}" />
  <input type="hidden" name="length_unit" value="{{length_unit}}" />
  <input type="hidden" name="weight" value="{{weight}}" />
  <input type="hidden" name="weight_unit" value="{{weight_unit}}" />
  <input type="hidden" name="result" value="{{result}}" />
  <input type="submit" value="SAVE MY BMI" name="save" />
</form>
<form action="{% url 'user:send_suggestions' %}" method="POST">
  {% csrf_token %}
  <input type="hidden" name="BMI_value" value="{{BMI}}" />
  <input type="hidden" name="height" value="{{height}}" />
  <input type="hidden" name="length_unit" value="{{length_unit}}" />
  <input type="hidden" name="weight" value="{{weight}}" />
  <input type="hidden" name="weight_unit" value="{{weight_unit}}" />
  <input type="hidden" name="result" value="{{result}}" />
  <input type="submit" value="Send Suggestions in Email" name="send" id="send" />
</form>

{% endblock content %} {% block suggestions %} {% endblock suggestions %}