BMIcalcapp/urls.py
from django.urls import path
from BMIcalcapp.views import bmi_calculator, bmi_data_entry, save_data, dashboard, delete_data

app_name = "BMIcalculator" 

urlpatterns = [
    path("entry/", bmi_data_entry, name="data_entry" ),
    path("calculate-bmi/", bmi_calculator, name="bmi_calculator"),
    path('save/', save_data, name="save"),
    path('dashboard/' ,dashboard, name="dashboard"),
    path('delete-data/', delete_data, name="delete"),
]
 

BMIcalculator/urls.py
from django.contrib import admin
from django.urls import path, include
from useraccount.views import home

app_name = "project"

urlpatterns = [
    path('', home, name="home"),
    path('admin/', admin.site.urls),
    path('bmi/', include("BMIcalcapp.urls", namespace="BMIcalculator")),
    path('user/', include('useraccount.urls', namespace="user")),
    path('verification/', include('verify_email.urls')),	

]

useraccount/urls.py
from django.urls import path
from useraccount.views import login_view, register_view, logout_view, send_suggestions, update_view
app_name = 'user'

urlpatterns = [
    path('login/', login_view, name="login"),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('send/', send_suggestions, name="send_suggestions"),
    path('update/', update_view, name="update"),
    # path('confirmation_page', send_confirmation, name="confirm"),
]

templates/components/navbar.html
<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-primary" >
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01"
      aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <a class="navbar-brand" href="{% url 'home' %}">BMI</a>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'BMIcalculator:data_entry' %}">Calculate BMI</a>
        </li>
      </ul>
      <form class="d-flex">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'user:logout' %}" id="logout">Logout</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'user:login' %}" id="login">Login
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'user:register' %}" id="register">
              Register
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'BMIcalculator:dashboard' %}" id="dashboard">
              See Profile
            </a>
          </li>
        </ul>
      </form>
    </div>
  </div>
</nav>